version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      nestjs:
        patterns:
          - "@nestjs/*"
      types:
        patterns:
          - "@types/*"
      dev-dependencies:
        dependency-type: "development"
        exclude-patterns:
          - "@nestjs/*"
          - "@types/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
