import type { RhinoConfig } from '../interfaces/rhino-config.interface';

export interface TypeScriptExporterOptions {
  /** Optional header comment prepended to the output. */
  header?: string;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generate a portable `.d.ts` string from an RhinoConfig.
 *
 * - One interface per registered model slug, using `allowedFields` for
 *   properties when available.
 * - A `${PascalSlug}Query` interface when `allowedFilters`, `allowedSorts`
 *   or `allowedSearch` are set.
 * - Generic helpers: `Paginated<T>`, `ApiResponse<T>`.
 * - A top-level `RhinoModels` union of all registered slugs.
 * - No Prisma-dependent imports.
 */
export function generateTypeScriptTypes(
  config: RhinoConfig,
  options: TypeScriptExporterOptions = {},
): string {
  const lines: string[] = [];

  // ---------- header ----------
  const header =
    options.header ??
    `// This file is auto-generated by Rhino. Do not edit manually.
// Generated: ${new Date().toISOString()}`;
  lines.push(header, '');

  // ---------- shared generics ----------
  lines.push(
    '/** Paginated list response returned by Rhino list endpoints. */',
    'export interface Paginated<T> {',
    '  data: T[];',
    '  meta: {',
    '    currentPage: number;',
    '    lastPage: number;',
    '    perPage: number;',
    '    total: number;',
    '  };',
    '}',
    '',
    '/** Generic API response wrapper used by single-resource endpoints. */',
    'export interface ApiResponse<T> {',
    '  data: T;',
    '}',
    '',
  );

  // ---------- permission helpers ----------
  lines.push(
    '/** A dot-separated permission string in the form `slug.action`. */',
    'export type Permission = string;',
    '',
    '/** Check whether `permission` appears in a list of `granted` permissions.',
    ' *  Supports wildcards: `*`, `{slug}.*`.',
    ' */',
    'export declare function matchesPermission(',
    '  permission: Permission,',
    '  granted: Permission[] | null | undefined,',
    '): boolean;',
    '',
  );

  const models = config.models ?? {};
  const slugs = Object.keys(models);

  // ---------- per-model interfaces ----------
  for (const slug of slugs) {
    const reg = models[slug];
    const ifaceName = slugToPascal(slug);

    // Model interface
    lines.push(`/** Rhino model interface for the '${slug}' resource. */`);
    lines.push(`export interface ${ifaceName} {`);

    const fields = reg.allowedFields ?? [];
    if (fields.length > 0) {
      for (const field of fields) {
        lines.push(`  ${sanitizeKey(field)}: string | number | boolean | null;`);
      }
    } else {
      // Minimal fallback when no field hints are available
      lines.push('  id: string | number;');
      lines.push('  [key: string]: unknown;');
    }

    lines.push('}', '');

    // Query interface — emit when there's at least one query hint
    const filters = reg.allowedFilters ?? [];
    const sorts = reg.allowedSorts ?? [];
    const search = reg.allowedSearch ?? [];
    const includes = reg.allowedIncludes ?? [];

    if (filters.length > 0 || sorts.length > 0 || search.length > 0 || includes.length > 0) {
      lines.push(`/** Query parameters accepted by the '${slug}' list endpoint. */`);
      lines.push(`export interface ${ifaceName}Query {`);

      if (filters.length > 0) {
        for (const f of filters) {
          lines.push(`  'filter[${f}]'?: string | number;`);
        }
      }

      if (sorts.length > 0) {
        const sortLiterals = [
          ...sorts.map(s => `'${s}'`),
          ...sorts.map(s => `'-${s}'`),
        ].join(' | ');
        lines.push(`  sort?: ${sortLiterals};`);
      }

      if (search.length > 0) {
        lines.push('  search?: string;');
      }

      if (includes.length > 0) {
        const includeLiterals = includes.map(i => `'${i}'`).join(' | ');
        lines.push(`  include?: ${includeLiterals};`);
      }

      if (reg.allowedFields && reg.allowedFields.length > 0) {
        lines.push(`  'fields[${slug}]'?: string;`);
      }

      if (reg.paginationEnabled !== false) {
        lines.push('  page?: number;');
        lines.push('  per_page?: number;');
      }

      lines.push('}', '');
    }
  }

  // ---------- RhinoModels union ----------
  if (slugs.length > 0) {
    const union = slugs.map(s => `'${s}'`).join(' | ');
    lines.push(
      '/** Union of all registered Rhino model slugs. */',
      `export type RhinoModels = ${union};`,
      '',
    );
  } else {
    lines.push(
      '/** Union of all registered Rhino model slugs (none registered). */',
      'export type RhinoModels = never;',
      '',
    );
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// CLI-compatible alias
// ---------------------------------------------------------------------------

/**
 * Alias for `generateTypeScriptTypes` used by the CLI command.
 *
 * @internal  Prefer `generateTypeScriptTypes` in library code.
 */
export function generate(
  config: RhinoConfig,
  options: TypeScriptExporterOptions = {},
): string {
  return generateTypeScriptTypes(config, options);
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Convert a slug like `blog-posts` or `blog_posts` to `BlogPosts`.
 */
function slugToPascal(slug: string): string {
  return slug
    .replace(/[-_](.)/g, (_, c: string) => c.toUpperCase())
    .replace(/^(.)/, (_, c: string) => c.toUpperCase());
}

/**
 * Wrap a property key in quotes if it contains characters that are not
 * valid unquoted TypeScript identifiers.
 */
function sanitizeKey(key: string): string {
  if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key)) return key;
  return `'${key}'`;
}
