/**
 * rhino generate
 *
 * Interactive wizard that asks:
 *   - What to create: model | policy | scope
 *   - Name (PascalCase)
 *   - Columns (for model only)
 *
 * Writes a stub file under the right directory.
 */
import * as path from 'path';
import {
  createInterface,
  ask,
  selectFromList,
  type ReadlineInterface,
} from '../utils/prompt';
import { writeFileSafely, fileExists } from '../utils/io';

export interface GenerateDeps {
  rl?: ReadlineInterface;
  cwd?: string;
}

export async function runGenerate(deps: GenerateDeps = {}): Promise<void> {
  const cwd = deps.cwd ?? process.cwd();
  const rl = deps.rl ?? createInterface();

  console.log('\n  Rhino :: Generate\n');

  const kind = await selectFromList(
    rl,
    'What would you like to generate?',
    ['model', 'policy', 'scope'],
    0,
  );

  const rawName = await ask(rl, `  Name (PascalCase, e.g. "BlogPost"): `);
  const name = toPascalCase(rawName);

  if (!name) {
    console.error('  Error: name is required.');
    rl.close();
    process.exit(1);
  }

  switch (kind) {
    case 'model':
      await generateModel(rl, cwd, name);
      break;
    case 'policy':
      generatePolicy(cwd, name);
      break;
    case 'scope':
      generateScope(cwd, name);
      break;
    default:
      console.error(`  Unknown type: ${kind}`);
      rl.close();
      process.exit(1);
  }

  rl.close();
}

// -----------------------------------------------------------------------
// Model
// -----------------------------------------------------------------------

async function generateModel(
  rl: ReadlineInterface,
  cwd: string,
  name: string,
): Promise<void> {
  const columnsRaw = await ask(
    rl,
    '  Columns (comma-separated, e.g. "title:string, body:text, published:boolean") []: ',
  );

  const columns = parseColumns(columnsRaw);
  const destPath = path.join(cwd, 'src', 'models', `${name}.model.ts`);

  if (fileExists(destPath)) {
    console.log(`  Skipped: ${destPath} already exists.`);
    return;
  }

  const content = renderModelStub(name, columns);
  writeFileSafely(destPath, content);
  console.log(`  Created: ${destPath}`);
}

function parseColumns(raw: string): Array<{ name: string; type: string }> {
  if (!raw.trim()) return [];
  return raw
    .split(',')
    .map((col) => col.trim())
    .filter(Boolean)
    .map((col) => {
      const [name, type = 'string'] = col.split(':').map((s) => s.trim());
      return { name: toCamelCase(name), type };
    });
}

function renderModelStub(
  name: string,
  columns: Array<{ name: string; type: string }>,
): string {
  const fieldLines = columns
    .map((c) => `  ${c.name}?: ${mapTsType(c.type)};`)
    .join('\n');

  return `/**
 * ${name} model stub — generated by \`npx rhino generate\`
 * Register in rhino.setup.ts:
 *   ${toCamelCase(name)}s: { model: '${name}' }
 */
import { RhinoModel } from '@rhino-dev/rhino-nestjs';

@RhinoModel()
export class ${name} {
  id!: number;
${fieldLines ? fieldLines + '\n' : ''}  createdAt?: Date;
  updatedAt?: Date;
}
`;
}

// -----------------------------------------------------------------------
// Policy
// -----------------------------------------------------------------------

function generatePolicy(cwd: string, name: string): void {
  const destPath = path.join(cwd, 'src', 'policies', `${name}.policy.ts`);

  if (fileExists(destPath)) {
    console.log(`  Skipped: ${destPath} already exists.`);
    return;
  }

  const content = renderPolicyStub(name);
  writeFileSafely(destPath, content);
  console.log(`  Created: ${destPath}`);
}

function renderPolicyStub(name: string): string {
  return `/**
 * ${name} policy stub — generated by \`npx rhino generate\`
 * Extend ResourcePolicy and override the methods you need.
 */
import { ResourcePolicy } from '@rhino-dev/rhino-nestjs';

export class ${name}Policy extends ResourcePolicy {
  // override index(user: any): boolean { ... }
  // override show(user: any, record: any): boolean { ... }
  // override store(user: any): boolean { ... }
  // override update(user: any, record: any): boolean { ... }
  // override destroy(user: any, record: any): boolean { ... }
}
`;
}

// -----------------------------------------------------------------------
// Scope
// -----------------------------------------------------------------------

function generateScope(cwd: string, name: string): void {
  const destPath = path.join(cwd, 'src', 'scopes', `${name}.scope.ts`);

  if (fileExists(destPath)) {
    console.log(`  Skipped: ${destPath} already exists.`);
    return;
  }

  const content = renderScopeStub(name);
  writeFileSafely(destPath, content);
  console.log(`  Created: ${destPath}`);
}

function renderScopeStub(name: string): string {
  return `/**
 * ${name} scope stub — generated by \`npx rhino generate\`
 * Implement the \`apply\` method to filter / order the default query.
 */
import type { RhinoScope } from '@rhino-dev/rhino-nestjs';

export class ${name}Scope implements RhinoScope {
  apply(query: Record<string, any>, _context: any): Record<string, any> {
    // Example: return { ...query, where: { ...query.where, deletedAt: null } };
    return query;
  }
}
`;
}

// -----------------------------------------------------------------------
// String helpers
// -----------------------------------------------------------------------

function toPascalCase(str: string): string {
  if (!str) return '';
  return str
    .replace(/[-_\s]+(.)/g, (_, c: string) => c.toUpperCase())
    .replace(/^(.)/, (c: string) => c.toUpperCase());
}

function toCamelCase(str: string): string {
  const pascal = toPascalCase(str);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

function mapTsType(prismaType: string): string {
  const map: Record<string, string> = {
    string: 'string',
    text: 'string',
    int: 'number',
    integer: 'number',
    float: 'number',
    decimal: 'number',
    boolean: 'boolean',
    bool: 'boolean',
    date: 'Date',
    datetime: 'Date',
    json: 'Record<string, unknown>',
  };
  return map[prismaType.toLowerCase()] ?? 'string';
}
