/**
 * rhino install
 *
 * Interactive setup wizard.  Prompts the user to:
 *   (a) configure a model-registration stub file
 *   (b) enable multi-tenant mode
 *   (c) set the org identifier column
 *   (d) scaffold an audit-trail Prisma model
 *   (e) install .claude/commands/ AI skill files from stubs/skills
 *
 * Writes a stub config to src/rhino.setup.ts.
 * Appends an AuditLog Prisma model snippet to prisma/schema.prisma.
 */
import * as path from 'path';
import * as fs from 'fs';
import {
  createInterface,
  ask,
  confirm,
  type ReadlineInterface,
} from '../utils/prompt';
import { writeFileSafely, appendIfMissing, fileExists } from '../utils/io';

const AUDIT_LOG_SNIPPET = `
model AuditLog {
  id         Int      @id @default(autoincrement())
  userId     Int?
  action     String   // create | update | delete
  modelName  String
  modelId    String
  oldValues  Json?
  newValues  Json?
  ipAddress  String?
  createdAt  DateTime @default(now())
}
`;

export interface InstallDeps {
  rl?: ReadlineInterface;
  cwd?: string;
  /** Override skill source dir (for tests). */
  skillsSourceDir?: string;
}

export async function runInstall(deps: InstallDeps = {}): Promise<void> {
  const cwd = deps.cwd ?? process.cwd();
  const rl = deps.rl ?? createInterface();

  console.log('\n  Rhino :: Install :: Let\'s build something great\n');

  // ---------------------------------------------------------------
  // (a) Model registration stub
  // ---------------------------------------------------------------
  const wantStub = await confirm(
    rl,
    'Create a model-registration stub file (src/rhino.setup.ts)?',
    true,
  );

  if (wantStub) {
    const stubPath = path.join(cwd, 'src', 'rhino.setup.ts');
    if (fileExists(stubPath)) {
      console.log(`  Skipped: ${stubPath} already exists.`);
    } else {
      const stubContent = generateSetupStub(false, 'id');
      writeFileSafely(stubPath, stubContent);
      console.log(`  Created: ${stubPath}`);
    }
  }

  // ---------------------------------------------------------------
  // (b) Multi-tenant
  // ---------------------------------------------------------------
  const wantMultiTenant = await confirm(
    rl,
    'Enable multi-tenant support (Organizations, Roles)?',
    false,
  );

  let orgIdentifierColumn = 'id';

  if (wantMultiTenant) {
    const col = await ask(
      rl,
      '  Which column identifies organizations? (id / slug / uuid) [id]: ',
    );
    orgIdentifierColumn = col || 'id';

    // Re-write the setup stub if it was already written
    const stubPath = path.join(cwd, 'src', 'rhino.setup.ts');
    if (fileExists(stubPath)) {
      const newContent = generateSetupStub(true, orgIdentifierColumn);
      writeFileSafely(stubPath, newContent);
      console.log(`  Updated: ${stubPath} (multi-tenant enabled)`);
    }
  }

  // ---------------------------------------------------------------
  // (d) Audit trail
  // ---------------------------------------------------------------
  const wantAudit = await confirm(
    rl,
    'Scaffold an AuditLog model in prisma/schema.prisma?',
    false,
  );

  if (wantAudit) {
    const schemaPath = path.join(cwd, 'prisma', 'schema.prisma');
    if (fileExists(schemaPath)) {
      const existing = fs.readFileSync(schemaPath, 'utf8');
      if (existing.includes('AuditLog')) {
        console.log('  Skipped: AuditLog already present in prisma/schema.prisma.');
      } else {
        fs.appendFileSync(schemaPath, `\n${AUDIT_LOG_SNIPPET}`, 'utf8');
        console.log(`  Appended AuditLog model to: ${schemaPath}`);
      }
    } else {
      console.log(
        '  Could not find prisma/schema.prisma — please add the following snippet manually:',
      );
      console.log(AUDIT_LOG_SNIPPET);
    }
  }

  // ---------------------------------------------------------------
  // (e) AI skill files
  // ---------------------------------------------------------------
  const wantSkills = await confirm(
    rl,
    'Install Rhino AI skills for Claude Code (.claude/commands/)?',
    true,
  );

  if (wantSkills) {
    await installSkills(cwd, deps.skillsSourceDir);
  }

  rl.close();

  console.log('\n  Rhino installed successfully!\n');
  console.log('  Next steps:');
  console.log('    1. Review src/rhino.setup.ts');
  console.log('    2. Add your blueprints to .rhino/blueprints/');
  console.log('    3. Run: npx rhino blueprint\n');
}

// -----------------------------------------------------------------------
// Helpers
// -----------------------------------------------------------------------

function generateSetupStub(
  multiTenant: boolean,
  orgIdentifierColumn: string,
): string {
  return `/**
 * Rhino setup — generated by \`npx rhino install\`
 * Adjust this file to match your application's model configuration.
 */
import { RhinoModule } from '@rhino-dev/rhino-nestjs';
// import { PrismaService } from './prisma/prisma.service';

export const rhinoConfig = {
  models: {
    // Register your models here, e.g.:
    // users: { model: 'User', policy: UserPolicy },
  },
  routeGroups: {
    default: {
      prefix: '',
      models: '*' as const,
    },
  },
  multiTenant: {
    enabled: ${multiTenant},
    organizationIdentifierColumn: '${orgIdentifierColumn}',
  },
  auth: {
    jwtSecret: process.env.JWT_SECRET ?? 'change-me',
    jwtExpiresIn: '7d',
    userModel: 'user',
    emailField: 'email',
    passwordField: 'password',
  },
};

// Add to your AppModule imports:
// RhinoModule.forRoot(rhinoConfig)
`;
}

async function installSkills(
  cwd: string,
  overrideSource?: string,
): Promise<void> {
  // The skills dir is shipped alongside the package under stubs/skills.
  // Resolve relative to this file so it works from both source and dist.
  const skillsSourceDir =
    overrideSource ??
    path.resolve(__dirname, '..', '..', '..', 'stubs', 'skills');

  const destDir = path.join(cwd, '.claude', 'commands');

  fs.mkdirSync(destDir, { recursive: true });

  if (!fileExists(skillsSourceDir)) {
    console.log(
      '  No skill files found (stubs/skills directory missing). Skipping.',
    );
    return;
  }

  const files = fs
    .readdirSync(skillsSourceDir)
    .filter((f) => f.startsWith('rhino-') && f.endsWith('.md'));

  if (files.length === 0) {
    console.log('  No rhino-*.md skill files found. Skipping.');
    return;
  }

  let installed = 0;
  for (const file of files) {
    const src = path.join(skillsSourceDir, file);
    const dest = path.join(destDir, file);
    fs.copyFileSync(src, dest);
    console.log(`  Installed: .claude/commands/${file}`);
    installed++;
  }

  console.log(`\n  ${installed} Rhino skills installed to .claude/commands/`);
  console.log(
    '  Run any skill in Claude Code: /rhino-feature, /rhino-review, etc.',
  );
}
