import type { Blueprint, BlueprintPermission } from '../blueprint-parser';

// ---------------------------------------------------------------------------
// PolicyGenerator
// ---------------------------------------------------------------------------

/**
 * Generates a TypeScript Policy class extending `ResourcePolicy`.
 *
 * The generated class overrides:
 *  - `permittedAttributesForShow`  — from `show_fields`
 *  - `hiddenAttributesForShow`     — from `hidden_fields`
 *  - `permittedAttributesForCreate` — from `create_fields`
 *  - `permittedAttributesForUpdate` — from `update_fields`
 *
 * Each method uses `this.hasRole(user, '<role>', org)` guards identical to the
 * Laravel reference implementation.
 */
export class PolicyGenerator {
  generate(blueprint: Blueprint): string {
    const { model, slug, permissions } = blueprint;
    const policyName = `${model}Policy`;

    const showMethod = this.buildPermittedMethod('permittedAttributesForShow', permissions, 'show_fields');
    const hiddenMethod = this.buildHiddenMethod(permissions);
    const createMethod = this.buildPermittedMethod('permittedAttributesForCreate', permissions, 'create_fields');
    const updateMethod = this.buildPermittedMethod('permittedAttributesForUpdate', permissions, 'update_fields');

    return [
      `// Generated by Rhino Blueprint — do not edit directly.`,
      `// Source: .rhino/blueprints/${blueprint.source_file}`,
      `import { ResourcePolicy } from '@rhino-dev/rhino-nestjs';`,
      ``,
      `/**`,
      ` * Authorization policy for the ${model} resource.`,
      ` * Regenerate with: npx rhino blueprint`,
      ` */`,
      `export class ${policyName} extends ResourcePolicy {`,
      `  override resourceSlug = '${slug}';`,
      ``,
      showMethod,
      ``,
      hiddenMethod,
      ``,
      createMethod,
      ``,
      updateMethod,
      `}`,
      ``,
    ].join('\n');
  }

  // -------------------------------------------------------------------------
  // Method builders
  // -------------------------------------------------------------------------

  /**
   * Build a `permittedAttributesFor*` method.
   * Groups roles with identical field sets to avoid repetitive if-branches.
   */
  buildPermittedMethod(
    methodName: string,
    permissions: Record<string, BlueprintPermission>,
    fieldKey: 'show_fields' | 'create_fields' | 'update_fields',
  ): string {
    if (Object.keys(permissions).length === 0) {
      return this.wrapMethod(methodName, `    return ['*'];`);
    }

    const groups = this.groupRolesByFields(permissions, fieldKey);
    const bodyLines: string[] = [];

    for (const { fields, roles } of groups) {
      const fieldArr = this.toFieldsArray(fields);
      if (!fieldArr || fieldArr.length === 0) continue; // skip roles with no fields

      const condition = this.buildCondition(roles);
      bodyLines.push(`    if (${condition}) {`);
      bodyLines.push(`      return ${this.fieldsToTsArray(fieldArr)};`);
      bodyLines.push(`    }`);
    }

    bodyLines.push(`    return [];`);
    return this.wrapMethod(methodName, bodyLines.join('\n'));
  }

  buildHiddenMethod(permissions: Record<string, BlueprintPermission>): string {
    const rolesWithHidden: Record<string, string[]> = {};
    for (const [role, def] of Object.entries(permissions)) {
      if (def.hidden_fields?.length > 0) {
        rolesWithHidden[role] = def.hidden_fields;
      }
    }

    if (Object.keys(rolesWithHidden).length === 0) {
      return this.wrapMethod('hiddenAttributesForShow', `    return [];`);
    }

    // Group by field set
    const groups = new Map<string, { fields: string[]; roles: string[] }>();
    for (const [role, fields] of Object.entries(rolesWithHidden)) {
      const key = JSON.stringify(fields);
      if (!groups.has(key)) groups.set(key, { fields, roles: [] });
      groups.get(key)!.roles.push(role);
    }

    const bodyLines: string[] = [];
    for (const { fields, roles } of groups.values()) {
      const condition = this.buildCondition(roles);
      bodyLines.push(`    if (${condition}) {`);
      bodyLines.push(`      return ${this.fieldsToTsArray(fields)};`);
      bodyLines.push(`    }`);
    }
    bodyLines.push(`    return [];`);
    return this.wrapMethod('hiddenAttributesForShow', bodyLines.join('\n'));
  }

  // -------------------------------------------------------------------------
  // Helpers
  // -------------------------------------------------------------------------

  /**
   * Group roles that share the same field set for a given field key.
   */
  groupRolesByFields(
    permissions: Record<string, BlueprintPermission>,
    fieldKey: 'show_fields' | 'create_fields' | 'update_fields',
  ): Array<{ fields: unknown; roles: string[] }> {
    const groups = new Map<string, { fields: unknown; roles: string[] }>();

    for (const [role, def] of Object.entries(permissions)) {
      const fields = def[fieldKey];
      const key = JSON.stringify(fields);
      if (!groups.has(key)) groups.set(key, { fields, roles: [] });
      groups.get(key)!.roles.push(role);
    }

    return Array.from(groups.values());
  }

  /**
   * Normalise `fields` to a string array or null.
   * - ['*'] / '*' → ['*']
   * - string[]    → as-is
   * - Record<string, string> → Object.keys(…)
   * - [] / {} / null → null (skip)
   */
  private toFieldsArray(fields: unknown): string[] | null {
    if (fields === '*' || (Array.isArray(fields) && fields[0] === '*')) return ['*'];
    if (Array.isArray(fields)) return fields.length > 0 ? (fields as string[]) : null;
    if (fields && typeof fields === 'object') {
      const keys = Object.keys(fields as object);
      return keys.length > 0 ? keys : null;
    }
    return null;
  }

  buildCondition(roles: string[]): string {
    const parts = roles.map((r) => `this.hasRole(user, '${r}', org)`);
    return parts.join(' ||\n      ');
  }

  fieldsToTsArray(fields: string[]): string {
    if (fields[0] === '*') return `['*']`;
    const items = fields.map((f) => `'${f}'`).join(', ');
    return `[${items}]`;
  }

  private wrapMethod(name: string, body: string): string {
    return [
      `  override ${name}(user: any, org?: any): string[] {`,
      body,
      `  }`,
    ].join('\n');
  }
}
