import type { Blueprint, BlueprintColumn, BlueprintPermission } from '../blueprint-parser';

// ---------------------------------------------------------------------------
// ResourceDefinitionGenerator
// ---------------------------------------------------------------------------

/**
 * Generates a TypeScript file that exports a `ModelRegistration` object.
 *
 * The output file:
 *  - imports `z` from zod and `ModelRegistration` from the library
 *  - builds `validationStore` and `validationUpdate` as `Record<string, ZodSchema>`
 *    keyed by role (from `permissions.*.create_fields` / `update_fields`)
 *  - sets `allowedFilters`, `allowedSorts`, `allowedSearch` from column flags
 *  - sets `belongsToOrganization`, `softDeletes`, `hasAuditTrail` flags
 *
 * Design decisions:
 *  - Field entries with value `'required'` → `z.string()` (non-optional)
 *  - Field entries with value `'nullable'` → `z.string().nullable().optional()`
 *  - Field entries with value `'sometimes'` → `z.string().optional()`
 *  - When create_fields / update_fields is `['*']` or empty, we emit a
 *    passthrough schema `z.object({}).passthrough()` as a permissive default.
 *  - If all roles share the same schema we still emit a role-keyed map for
 *    uniformity (the runtime ValidationService uses the map form).
 */
export class ResourceDefinitionGenerator {
  generate(blueprint: Blueprint): string {
    const lines: string[] = [];

    lines.push(`// Generated by Rhino Blueprint — do not edit directly.`);
    lines.push(`// Source: .rhino/blueprints/${blueprint.source_file}`);
    lines.push(`import { z } from 'zod';`);
    lines.push(`import type { ModelRegistration } from '@rhino-project/rhino-nestjs';`);
    lines.push('');

    // Policy import (generated separately)
    lines.push(`import { ${blueprint.model}Policy } from '../policies/${blueprint.model}Policy';`);
    lines.push('');

    // Zod schemas per role
    const storeSchemas = this.buildRoleSchemas(blueprint, 'create_fields');
    const updateSchemas = this.buildRoleSchemas(blueprint, 'update_fields');

    lines.push('// ---------------------------------------------------------------------------');
    lines.push('// Validation schemas per role');
    lines.push('// ---------------------------------------------------------------------------');
    lines.push('');
    lines.push('const validationStore: Record<string, z.ZodTypeAny> = {');
    for (const [role, schemaCode] of Object.entries(storeSchemas)) {
      lines.push(`  ${role}: ${schemaCode},`);
    }
    lines.push('};');
    lines.push('');
    lines.push('const validationUpdate: Record<string, z.ZodTypeAny> = {');
    for (const [role, schemaCode] of Object.entries(updateSchemas)) {
      lines.push(`  ${role}: ${schemaCode},`);
    }
    lines.push('};');
    lines.push('');

    // Allowed query options from column flags
    const allowedFilters = blueprint.columns.filter((c) => c.filterable).map((c) => c.name);
    const allowedSorts = blueprint.columns.filter((c) => c.sortable).map((c) => c.name);
    const allowedSearch = blueprint.columns.filter((c) => c.searchable).map((c) => c.name);

    lines.push('// ---------------------------------------------------------------------------');
    lines.push('// ModelRegistration');
    lines.push('// ---------------------------------------------------------------------------');
    lines.push('');
    lines.push(`export const ${this.camelCase(blueprint.slug)}Registration: ModelRegistration = {`);
    lines.push(`  model: '${this.camelCase(blueprint.model)}',`);
    lines.push(`  policy: ${blueprint.model}Policy,`);
    lines.push(`  validationStore,`);
    lines.push(`  validationUpdate,`);

    if (allowedFilters.length > 0) {
      lines.push(`  allowedFilters: ${JSON.stringify(allowedFilters)},`);
    }
    if (allowedSorts.length > 0) {
      lines.push(`  allowedSorts: ${JSON.stringify(allowedSorts)},`);
    }
    if (allowedSearch.length > 0) {
      lines.push(`  allowedSearch: ${JSON.stringify(allowedSearch)},`);
    }

    lines.push(`  belongsToOrganization: ${blueprint.options.belongs_to_organization},`);
    lines.push(`  softDeletes: ${blueprint.options.soft_deletes},`);
    lines.push(`  hasAuditTrail: ${blueprint.options.audit_trail},`);
    if (blueprint.options.has_uuid) {
      // BP-005: surface the flag so ResourceService.castId preserves string IDs
      lines.push(`  hasUuid: true,`);
    }

    // BP-004: emit `owner` / `fkConstraints` from YAML when declared so
    // ValidationService.verifyTenantFks (and the FK chain walker) can do
    // cross-tenant validation without a hand-authored override.
    const ownerStr = blueprint.options.owner_chain ?? blueprint.options.owner ?? null;
    if (ownerStr) {
      lines.push(`  owner: ${JSON.stringify(ownerStr)},`);
    }
    if (blueprint.fk_constraints?.length > 0) {
      lines.push(`  fkConstraints: ${JSON.stringify(blueprint.fk_constraints)},`);
    }

    if (blueprint.options.except_actions?.length > 0) {
      lines.push(`  exceptActions: ${JSON.stringify(blueprint.options.except_actions)},`);
    }

    lines.push(`};`);
    lines.push('');

    return lines.join('\n');
  }

  // -------------------------------------------------------------------------
  // Private helpers
  // -------------------------------------------------------------------------

  /**
   * Build a map of role → Zod schema code string for a given field surface
   * ('create_fields' or 'update_fields').
   */
  private buildRoleSchemas(
    blueprint: Blueprint,
    surface: 'create_fields' | 'update_fields',
  ): Record<string, string> {
    const result: Record<string, string> = {};

    for (const [role, perm] of Object.entries(blueprint.permissions)) {
      result[role] = this.buildZodSchema(perm, surface, blueprint.columns);
    }

    return result;
  }

  private buildZodSchema(
    perm: BlueprintPermission,
    surface: 'create_fields' | 'update_fields',
    columns: BlueprintColumn[],
  ): string {
    const fields = perm[surface];

    // Wildcard → passthrough permissive schema
    if (Array.isArray(fields) && fields[0] === '*') {
      return `z.object({}).passthrough()`;
    }

    // Array form (no presence modifiers) — BP-003: infer required from
    // the column's `nullable: false` declaration. This lets blueprints
    // express "required title" purely via the column definition, without
    // forcing the object form { title: required } on every permission.
    if (Array.isArray(fields)) {
      if (fields.length === 0) return `z.object({})`;
      const entries = fields.map((f) => {
        const col = columns.find((c) => c.name === f);
        // For create surface: non-nullable column → required; nullable → optional/nullable.
        // For update surface: always optional (partial update semantics); keep nullable.
        const presence = this.inferPresenceFromColumn(col, surface);
        return `    ${f}: ${this.zodTypeForColumn(f, columns, presence)}`;
      });
      return `z.object({\n${entries.join(',\n')},\n  })`;
    }

    // Object form: { fieldName: 'required' | 'nullable' | 'sometimes' }
    const entries = Object.entries(fields ?? {}).map(([field, presence]) => {
      const zodType = this.zodTypeForColumn(field, columns, presence);
      return `    ${field}: ${zodType}`;
    });

    // Empty object — role has no writable fields (e.g. read-only roles)
    if (entries.length === 0) return `z.object({})`;

    return `z.object({\n${entries.join(',\n')},\n  })`;
  }

  /**
   * BP-003: derive presence from a column's `nullable` flag when no explicit
   * modifier was given.
   *
   *   nullable: false, no default → 'required' on create, 'sometimes' on update
   *   nullable: false, has default → 'sometimes' on both (DB will fill in)
   *   nullable: true               → 'nullable' on both surfaces
   *
   * Fallback to 'optional' when the column isn't declared (unlikely but safe).
   */
  private inferPresenceFromColumn(
    col: BlueprintColumn | undefined,
    surface: 'create_fields' | 'update_fields',
  ): string {
    if (!col) return 'optional';
    if (col.nullable) return 'nullable';
    // BP-003 followup: columns with a default value can be omitted on create
    // — the DB (or Prisma @default) supplies the value.
    if (col.default !== null && col.default !== undefined) return 'sometimes';
    return surface === 'create_fields' ? 'required' : 'sometimes';
  }

  /**
   * Determine the Zod type for a single field based on its column definition and presence modifier.
   *
   * Presence values:
   *   'required'  → z.string()           (must be present, not null)
   *   'nullable'  → z.string().nullable().optional()
   *   'sometimes' → z.string().optional()
   *   'optional'  → z.string().optional()  (when presence not specified)
   */
  private zodTypeForColumn(
    fieldName: string,
    columns: BlueprintColumn[],
    presence: string,
  ): string {
    const col = columns.find((c) => c.name === fieldName);
    const baseType = col ? this.zodBaseType(col) : 'z.string()';

    switch (presence) {
      case 'required':
        return baseType;
      case 'nullable':
        return `${baseType}.nullable().optional()`;
      case 'sometimes':
      case 'optional':
        return `${baseType}.optional()`;
      default:
        return `${baseType}.optional()`;
    }
  }

  private zodBaseType(col: BlueprintColumn): string {
    switch (col.type) {
      case 'string':
      case 'text':
      case 'uuid':
        return 'z.string()';
      case 'integer':
      case 'bigInteger':
      case 'foreignId':
        return 'z.number().int()';
      case 'float':
      case 'decimal':
        return 'z.number()';
      case 'boolean':
        return 'z.boolean()';
      case 'date':
      case 'datetime':
      case 'timestamp':
        return 'z.string().datetime({ offset: true }).or(z.date())';
      case 'json':
        return 'z.record(z.unknown())';
      case 'enum':
        if (col.values?.length) {
          const vals = col.values.map((v) => `'${v}'`) .join(', ');
          return `z.enum([${vals}])`;
        }
        return 'z.string()';
      default:
        return 'z.string()';
    }
  }

  private camelCase(str: string): string {
    return str.replace(/[-_](.)/g, (_, c: string) => c.toUpperCase());
  }
}
