import type { Blueprint, BlueprintColumn } from '../blueprint-parser';

// ---------------------------------------------------------------------------
// SeederGenerator
// ---------------------------------------------------------------------------

/**
 * Generates a TypeScript seeder file for a Blueprint resource.
 *
 * The generated file exports an async `seed` function that creates a small
 * number of sample rows via the Prisma client.
 *
 * Design decisions:
 *  - We generate 3 sample rows with slightly varied data.
 *  - `organizationId` defaults to 1 when `belongs_to_organization` is true.
 *  - The seeder is a plain async function — not a NestJS service — so it can
 *    be run standalone via `ts-node src/seeders/<Model>Seeder.ts`.
 */
export class SeederGenerator {
  generate(blueprint: Blueprint): string {
    const { model, options, columns } = blueprint;
    const prismaModel = this.camelCase(model);

    const lines: string[] = [];

    lines.push(`// Generated by Rhino Blueprint — do not edit directly.`);
    lines.push(`// Source: .rhino/blueprints/${blueprint.source_file}`);
    lines.push(`import { PrismaClient } from '@prisma/client';`);
    lines.push(``);
    lines.push(`const prisma = new PrismaClient();`);
    lines.push(``);
    lines.push(`/**`);
    lines.push(` * Seed sample ${model} rows.`);
    lines.push(` * Run: npx ts-node src/seeders/${model}Seeder.ts`);
    lines.push(` */`);
    lines.push(`export async function seed(): Promise<void> {`);
    lines.push(`  console.log('Seeding ${model}...');`);
    lines.push(``);

    const rows = [1, 2, 3].map((i) => this.buildRow(blueprint, i));

    for (let i = 0; i < rows.length; i++) {
      lines.push(`  await prisma.${prismaModel}.upsert({`);
      // BP-005: UUID-PK models need string ids, not integer ids.
      if (blueprint.options.has_uuid) {
        const uuid = `00000000-0000-0000-0000-00000000000${i + 1}`;
        lines.push(`    where: { id: '${uuid}' },`);
      } else {
        lines.push(`    where: { id: ${i + 1} },`);
      }
      lines.push(`    update: {},`);
      lines.push(`    create: ${this.formatObject(rows[i], 4)},`);
      lines.push(`  });`);
      lines.push(``);
    }

    lines.push(`  console.log('✓ ${model} seeded (${rows.length} rows)');`);
    lines.push(`}`);
    lines.push(``);
    lines.push(`// Allow running directly`);
    lines.push(`if (require.main === module) {`);
    lines.push(`  seed()`);
    lines.push(`    .catch(console.error)`);
    lines.push(`    .finally(() => prisma.$disconnect());`);
    lines.push(`}`);
    lines.push(``);

    return lines.join('\n');
  }

  // -------------------------------------------------------------------------
  // Private helpers
  // -------------------------------------------------------------------------

  private buildRow(blueprint: Blueprint, index: number): Record<string, unknown> {
    // BP-005: UUID-PK models use deterministic UUID strings so seed is
    // idempotent (upsert where id:'00...001' etc.).
    const id = blueprint.options.has_uuid
      ? `00000000-0000-0000-0000-00000000000${index}`
      : index;
    const row: Record<string, unknown> = { id };

    if (blueprint.options.belongs_to_organization) {
      row['organizationId'] = 1;
    }

    for (const col of blueprint.columns) {
      row[col.name] = this.sampleValue(col, index);
    }

    return row;
  }

  private sampleValue(col: BlueprintColumn, index: number): unknown {
    if (col.default !== null && col.default !== undefined) {
      // Use default when available
      return col.default;
    }

    switch (col.type) {
      case 'string':
        return `Sample ${this.humanize(col.name)} ${index}`;
      case 'text':
        return `Sample ${this.humanize(col.name)} content for row ${index}.`;
      case 'integer':
      case 'bigInteger':
        return index * 10;
      case 'foreignId':
        return 1; // reference first record
      case 'float':
      case 'decimal':
        return parseFloat((index * 9.99).toFixed(2));
      case 'boolean':
        return index % 2 === 1;
      case 'date':
      case 'datetime':
      case 'timestamp':
        return new Date(`2024-0${index}-01T00:00:00Z`).toISOString();
      case 'json':
        return { sample: true, index };
      case 'uuid':
        return `00000000-0000-0000-0000-00000000000${index}`;
      case 'enum':
        return col.values?.[0] ?? 'draft';
      default:
        return `value_${index}`;
    }
  }

  private humanize(name: string): string {
    return name.replace(/[_-]/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
  }

  private formatObject(obj: Record<string, unknown>, indent: number): string {
    const pad = ' '.repeat(indent);
    const innerPad = ' '.repeat(indent + 2);
    const entries = Object.entries(obj).map(([k, v]) => {
      const val = JSON.stringify(v);
      return `${innerPad}${k}: ${val}`;
    });
    return `{\n${entries.join(',\n')},\n${pad}}`;
  }

  private camelCase(str: string): string {
    const pascal = str.replace(/[-_](.)/g, (_, c: string) => c.toUpperCase());
    return pascal.charAt(0).toLowerCase() + pascal.slice(1);
  }
}
