import type { Blueprint } from '../blueprint-parser';

/**
 * Generates a Jest spec for a blueprint resource.
 *
 * Produces a self-contained file using the library's `buildEnv` helper, which
 * the library ships under `test/helpers/make-controller.ts`. Consumer apps
 * can copy that helper into their own test tree or replace the import path
 * with their own equivalent — a comment in the generated file explains how.
 *
 * Tests produced:
 *   1. CRUD happy-path (index / show / store / update / destroy)
 *   2. 403 when a restricted role attempts a write action
 *   3. 404 for cross-tenant access (when `belongs_to_organization: true`)
 *
 * Controller invocation uses the real `GlobalController` public method
 * signatures:  `index(modelSlug, query, req)`, `show(modelSlug, id, query, req)`,
 * `store(modelSlug, body, req)`, `update(modelSlug, id, body, req)`,
 * `destroy(modelSlug, id, req)`.
 */
export class TestGenerator {
  generate(blueprint: Blueprint): string {
    const { model, slug, options, permissions } = blueprint;
    const roles = Object.keys(permissions);
    const adminRole = roles.find((r) => r === 'admin') ?? roles[0] ?? 'admin';
    const restrictedRole = roles.find((r) => {
      const actions = permissions[r]?.actions ?? [];
      return !actions.includes('store') || !actions.includes('update') || !actions.includes('destroy');
    });

    const modelKey = this.camelCase(model);
    const sampleRow = this.buildSampleRow(blueprint);
    const createPayload = this.buildCreatePayload(blueprint);
    const updatePayload = this.buildUpdatePayload(blueprint);
    const adminPerms = this.permissionsFor(slug, permissions[adminRole]);
    // BP-005: UUID-PK models use strings in Prisma `where: { id: '...' }`.
    const sampleId: any = options.has_uuid
      ? sampleRow.id // already UUID from buildSampleRow
      : 1;
    const idLiteral = options.has_uuid ? `'${sampleId}'` : '1';
    const idRouteParam = options.has_uuid ? `'${sampleId}'` : "'1'";

    const lines: string[] = [];
    const push = (s = '') => lines.push(s);

    push(`// Generated by Rhino Blueprint — do not edit directly.`);
    push(`// Source: .rhino/blueprints/${blueprint.source_file}`);
    push(`// NOTE: this spec imports \`buildEnv\` from the library test helper.`);
    push(`// For your app, replace the import with your own test helper or the`);
    push(`// published helper re-exported from \`@rhino-dev/rhino-nestjs/testing\`.`);
    push(`import { buildEnv } from '../../test/helpers/make-controller';`);
    push(`import type { RhinoConfig } from '@rhino-dev/rhino-nestjs';`);
    push(``);

    // Config helper
    push(`function makeConfig(overrides: Partial<RhinoConfig> = {}): RhinoConfig {`);
    push(`  return {`);
    push(`    models: {`);
    push(`      ${slug}: {`);
    push(`        model: '${modelKey}',`);
    push(`        belongsToOrganization: ${options.belongs_to_organization},`);
    push(`        softDeletes: ${options.soft_deletes},`);
    push(`        hasAuditTrail: ${options.audit_trail},`);
    push(`      },`);
    push(`    },`);
    push(`    ...overrides,`);
    push(`  };`);
    push(`}`);
    push(``);

    // User helper — matches the shape consumed by permission-matcher.ts
    push(`/** Build a user with a role + permissions for the target organization. */`);
    push(`function makeUser(role: string, perms: string[] = [], orgId = 1) {`);
    push(`  return {`);
    push(`    id: 1,`);
    push(`    userRoles: [`);
    push(`      { organizationId: orgId, permissions: perms, role: { slug: role } },`);
    push(`    ],`);
    push(`  };`);
    push(`}`);
    push(``);

    push(`const sampleRow = ${JSON.stringify(sampleRow, null, 2)};`);
    push(`const adminPerms = ${JSON.stringify(adminPerms)};`);
    push(``);

    push(`describe('${model} resource', () => {`);

    // Happy path
    push(`  // -----------------------------------------------------------------`);
    push(`  // CRUD happy path`);
    push(`  // -----------------------------------------------------------------`);
    push(``);
    push(`  it('index returns records for the current org', async () => {`);
    push(`    const env = buildEnv(makeConfig(), { ${modelKey}: [sampleRow] });`);
    push(`    const user = makeUser('${adminRole}', adminPerms);`);
    push(`    const req = { user, organization: { id: 1 } } as any;`);
    push(`    const res: any = await env.controllers.global.index('${slug}', {}, req);`);
    push(`    expect(res).toBeDefined();`);
    push(`  });`);
    push(``);
    push(`  it('show returns a single record by id', async () => {`);
    push(`    const env = buildEnv(makeConfig(), { ${modelKey}: [{ ...sampleRow, id: ${idLiteral} }] });`);
    push(`    const user = makeUser('${adminRole}', adminPerms);`);
    push(`    const req = { user, organization: { id: 1 } } as any;`);
    push(`    const res: any = await env.controllers.global.show('${slug}', ${idRouteParam}, {}, req);`);
    push(`    expect(res).toMatchObject({ id: ${idLiteral} });`);
    push(`  });`);
    push(``);
    push(`  it('store persists a new record', async () => {`);
    push(`    const env = buildEnv(makeConfig());`);
    push(`    const user = makeUser('${adminRole}', adminPerms);`);
    push(`    const req = { user, organization: { id: 1 } } as any;`);
    push(`    const body = ${JSON.stringify(createPayload)};`);
    push(`    await env.controllers.global.store('${slug}', body, req);`);
    push(`    const rows = env.client._data.${modelKey} ?? [];`);
    push(`    expect(rows.length).toBeGreaterThan(0);`);
    push(`  });`);
    push(``);
    push(`  it('update modifies an existing record', async () => {`);
    push(`    const env = buildEnv(makeConfig(), { ${modelKey}: [{ ...sampleRow, id: ${idLiteral} }] });`);
    push(`    const user = makeUser('${adminRole}', adminPerms);`);
    push(`    const req = { user, organization: { id: 1 } } as any;`);
    push(`    const body = ${JSON.stringify(updatePayload)};`);
    push(`    const res: any = await env.controllers.global.update('${slug}', ${idRouteParam}, body, req);`);
    push(`    expect(res).toBeDefined();`);
    push(`  });`);
    push(``);
    push(`  it('destroy removes (or soft-deletes) the record', async () => {`);
    push(`    const env = buildEnv(makeConfig(), { ${modelKey}: [{ ...sampleRow, id: ${idLiteral} }] });`);
    push(`    const user = makeUser('${adminRole}', adminPerms);`);
    push(`    const req = { user, organization: { id: 1 } } as any;`);
    push(`    await env.controllers.global.destroy('${slug}', ${idRouteParam}, req);`);
    push(`    const rows = env.client._data.${modelKey} ?? [];`);
    push(`    const active = rows.filter((r: any) => !r.deletedAt);`);
    push(`    expect(active).toHaveLength(0);`);
    push(`  });`);
    push(``);

    // 403 restricted role
    if (restrictedRole) {
      const restrictedPerms = this.permissionsFor(slug, permissions[restrictedRole]);
      push(`  // -----------------------------------------------------------------`);
      push(`  // 403 — role without store permission`);
      push(`  // -----------------------------------------------------------------`);
      push(``);
      push(`  it('rejects store from a role without store permission', async () => {`);
      push(`    const env = buildEnv(makeConfig());`);
      push(`    const user = makeUser('${restrictedRole}', ${JSON.stringify(restrictedPerms)});`);
      push(`    const req = { user, organization: { id: 1 } } as any;`);
      push(`    const body = ${JSON.stringify(createPayload)};`);
      push(`    // Without \`${slug}.store\` in permissions, the policy check will reject.`);
      push(`    // The exact exception type depends on how the route is guarded;`);
      push(`    // here we assert store throws (not persists).`);
      push(`    await expect(`);
      push(`      env.controllers.global.store('${slug}', body, req),`);
      push(`    ).rejects.toBeDefined();`);
      push(`  });`);
      push(``);
    }

    // 404 cross-tenant
    if (options.belongs_to_organization) {
      push(`  // -----------------------------------------------------------------`);
      push(`  // 404 — cross-tenant access`);
      push(`  // -----------------------------------------------------------------`);
      push(``);
      push(`  it('does not return records belonging to another organization', async () => {`);
      push(`    const env = buildEnv(makeConfig(), {`);
      push(`      ${modelKey}: [{ ...sampleRow, id: ${idLiteral}, organizationId: 99 }],`);
      push(`    });`);
      push(`    const user = makeUser('${adminRole}', adminPerms, 1);`);
      push(`    const req = { user, organization: { id: 1 } } as any;`);
      push(`    await expect(`);
      push(`      env.controllers.global.show('${slug}', ${idRouteParam}, {}, req),`);
      push(`    ).rejects.toMatchObject({ code: 'NOT_FOUND' });`);
      push(`  });`);
      push(``);
    }

    push(`});`);
    push(``);
    return lines.join('\n');
  }

  // -------------------------------------------------------------------------
  // Helpers
  // -------------------------------------------------------------------------

  private permissionsFor(slug: string, perm?: { actions?: string[] }): string[] {
    if (!perm?.actions) return [];
    if (perm.actions.includes('*')) return [`${slug}.*`];
    return perm.actions.map((a) => `${slug}.${a}`);
  }

  private buildSampleRow(blueprint: Blueprint): Record<string, unknown> {
    // BP-005: UUID-PK models emit a deterministic UUID sample so generated
    // tests pass Prisma's `where: { id: '...' }` validation.
    const id: number | string = blueprint.options.has_uuid
      ? '00000000-0000-0000-0000-000000000001'
      : 1;
    const row: Record<string, unknown> = { id };
    for (const col of blueprint.columns) {
      row[col.name] = this.sampleValue(col.type, col.values);
    }
    if (blueprint.options.belongs_to_organization) row['organizationId'] = 1;
    return row;
  }

  private buildCreatePayload(blueprint: Blueprint): Record<string, unknown> {
    const payload: Record<string, unknown> = {};
    const adminPerm = Object.values(blueprint.permissions)[0];
    if (!adminPerm) {
      for (const col of blueprint.columns) payload[col.name] = this.sampleValue(col.type, col.values);
      return payload;
    }
    const createFields = adminPerm.create_fields;
    if (!createFields || (Array.isArray(createFields) && createFields[0] === '*')) {
      for (const col of blueprint.columns) payload[col.name] = this.sampleValue(col.type, col.values);
      return payload;
    }
    const fieldNames = Array.isArray(createFields) ? createFields : Object.keys(createFields);
    for (const name of fieldNames) {
      const col = blueprint.columns.find((c) => c.name === name);
      payload[name] = this.sampleValue(col?.type ?? 'string', col?.values);
    }
    return payload;
  }

  private buildUpdatePayload(blueprint: Blueprint): Record<string, unknown> {
    const payload: Record<string, unknown> = {};
    const firstPerm = Object.values(blueprint.permissions)[0];
    if (!firstPerm) return payload;
    const updateFields = firstPerm.update_fields;
    if (!updateFields || (Array.isArray(updateFields) && updateFields[0] === '*')) {
      const col = blueprint.columns[0];
      if (col) payload[col.name] = this.sampleValue(col.type, col.values);
      return payload;
    }
    const fieldNames = Array.isArray(updateFields) ? updateFields : Object.keys(updateFields);
    const name = fieldNames[0];
    if (name) {
      const col = blueprint.columns.find((c) => c.name === name);
      payload[name] = this.sampleValue(col?.type ?? 'string', col?.values);
    }
    return payload;
  }

  private sampleValue(type: string, enumValues?: string[]): unknown {
    switch (type) {
      case 'string':
      case 'text':
        return 'sample text';
      case 'integer':
      case 'bigInteger':
      case 'foreignId':
        return 1;
      case 'float':
      case 'decimal':
        return 1.5;
      case 'boolean':
        return true;
      case 'date':
      case 'datetime':
      case 'timestamp':
        return '2024-01-01T00:00:00Z';
      case 'json':
        return {};
      case 'uuid':
        return '00000000-0000-0000-0000-000000000000';
      case 'enum':
        return enumValues?.[0] ?? 'draft';
      default:
        return 'value';
    }
  }

  private camelCase(str: string): string {
    if (!str) return str;
    return str.charAt(0).toLowerCase() + str.slice(1).replace(/[-_](.)/g, (_, c: string) => c.toUpperCase());
  }
}
